version: '2'
services:
  homeassistant:
    image: 'homeassistant/home-assistant:stable'
    container_name: homeassistant
    environment:
      - TZ=Europe/Paris
    ports:
      - '8123:8123'
    volumes:
      - '/home/clement/docker/homeassistant/config:/config'
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - '/home/clement/docker/mosquitto/config:/mosquitto/config'
      - 'mosquitto_data:/mosquitto/data'
      - 'mosquitto_log:/mosquitto/log'
    restart: unless-stopped
  zigbee2mqtt:
    image: 'koenkk/zigbee2mqtt:latest'
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - '/home/clement/docker/zigbee2mqtt:/app/data'
      - '/run/udev:/run/udev:ro'
    ports:
      - '8089:8089'
    devices:
      - '/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509183036-if00:/dev/ttyACM0'
    restart: unless-stopped
volumes:
  homeassistant_config: 
  mosquitto_data: 
  mosquitto_log:
